// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/error.dart';
import 'api/session.dart';
import 'api/status.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class OnionCoreApiImplPlatform extends BaseApiImpl<OnionCoreWire> {
  OnionCoreApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TorServicePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorServicePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TorSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSessionPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  TorService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  );

  @protected
  TorSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  );

  @protected
  TorService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  );

  @protected
  TorSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  );

  @protected
  TorService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  );

  @protected
  TorSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<TorStatus> dco_decode_StreamSink_tor_status_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Blockage dco_decode_blockage(dynamic raw);

  @protected
  BlockageKind dco_decode_blockage_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Blockage dco_decode_box_autoadd_blockage(dynamic raw);

  @protected
  TorStatus dco_decode_box_autoadd_tor_status(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Blockage? dco_decode_opt_box_autoadd_blockage(dynamic raw);

  @protected
  SocksPolicy dco_decode_socks_policy(dynamic raw);

  @protected
  TorFailure dco_decode_tor_failure(dynamic raw);

  @protected
  TorFailureKind dco_decode_tor_failure_kind(dynamic raw);

  @protected
  TorStatus dco_decode_tor_status(dynamic raw);

  @protected
  TorTransport dco_decode_tor_transport(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  TorService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  );

  @protected
  TorSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  );

  @protected
  TorService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  );

  @protected
  TorSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  );

  @protected
  TorService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  );

  @protected
  TorSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TorStatus> sse_decode_StreamSink_tor_status_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Blockage sse_decode_blockage(SseDeserializer deserializer);

  @protected
  BlockageKind sse_decode_blockage_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Blockage sse_decode_box_autoadd_blockage(SseDeserializer deserializer);

  @protected
  TorStatus sse_decode_box_autoadd_tor_status(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Blockage? sse_decode_opt_box_autoadd_blockage(SseDeserializer deserializer);

  @protected
  SocksPolicy sse_decode_socks_policy(SseDeserializer deserializer);

  @protected
  TorFailure sse_decode_tor_failure(SseDeserializer deserializer);

  @protected
  TorFailureKind sse_decode_tor_failure_kind(SseDeserializer deserializer);

  @protected
  TorStatus sse_decode_tor_status(SseDeserializer deserializer);

  @protected
  TorTransport sse_decode_tor_transport(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_tor_status_Dco(RustStreamSink<TorStatus> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_tor_status,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_blockage> cst_encode_box_autoadd_blockage(Blockage raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_blockage();
    cst_api_fill_to_wire_blockage(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_tor_status> cst_encode_box_autoadd_tor_status(
    TorStatus raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_tor_status();
    cst_api_fill_to_wire_tor_status(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_blockage> cst_encode_opt_box_autoadd_blockage(
    Blockage? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_blockage(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_blockage(
    Blockage apiObj,
    wire_cst_blockage wireObj,
  ) {
    wireObj.kind = cst_encode_blockage_kind(apiObj.kind);
    wireObj.message = cst_encode_String(apiObj.message);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_blockage(
    Blockage apiObj,
    ffi.Pointer<wire_cst_blockage> wireObj,
  ) {
    cst_api_fill_to_wire_blockage(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_tor_status(
    TorStatus apiObj,
    ffi.Pointer<wire_cst_tor_status> wireObj,
  ) {
    cst_api_fill_to_wire_tor_status(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_tor_failure(
    TorFailure apiObj,
    wire_cst_tor_failure wireObj,
  ) {
    wireObj.kind = cst_encode_tor_failure_kind(apiObj.kind);
    wireObj.log_message = cst_encode_String(apiObj.logMessage);
  }

  @protected
  void cst_api_fill_to_wire_tor_status(
    TorStatus apiObj,
    wire_cst_tor_status wireObj,
  ) {
    wireObj.fraction = cst_encode_f_32(apiObj.fraction);
    wireObj.ready_for_traffic = cst_encode_bool(apiObj.readyForTraffic);
    wireObj.blockage = cst_encode_opt_box_autoadd_blockage(apiObj.blockage);
    wireObj.transport = cst_encode_tor_transport(apiObj.transport);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  );

  @protected
  int cst_encode_blockage_kind(BlockageKind raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_socks_policy(SocksPolicy raw);

  @protected
  int cst_encode_tor_failure_kind(TorFailureKind raw);

  @protected
  int cst_encode_tor_transport(TorTransport raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tor_status_Dco(
    RustStreamSink<TorStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_blockage(Blockage self, SseSerializer serializer);

  @protected
  void sse_encode_blockage_kind(BlockageKind self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_blockage(Blockage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tor_status(
    TorStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_blockage(
    Blockage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_socks_policy(SocksPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_tor_failure(TorFailure self, SseSerializer serializer);

  @protected
  void sse_encode_tor_failure_kind(
    TorFailureKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tor_status(TorStatus self, SseSerializer serializer);

  @protected
  void sse_encode_tor_transport(TorTransport self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class OnionCoreWire implements BaseWire {
  factory OnionCoreWire.fromExternalLibrary(ExternalLibrary lib) =>
      OnionCoreWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OnionCoreWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OnionCoreWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__client__TorService_bootstrap(int port_, int that) {
    return _wire__crate__api__client__TorService_bootstrap(port_, that);
  }

  late final _wire__crate__api__client__TorService_bootstrapPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__client__TorService_bootstrap',
      );
  late final _wire__crate__api__client__TorService_bootstrap =
      _wire__crate__api__client__TorService_bootstrapPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__client__TorService_open_session(
    int port_,
    int that,
    int socks_port,
    int policy,
  ) {
    return _wire__crate__api__client__TorService_open_session(
      port_,
      that,
      socks_port,
      policy,
    );
  }

  late final _wire__crate__api__client__TorService_open_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Uint16, ffi.Int32)
        >
      >('frbgen_onion_wire__crate__api__client__TorService_open_session');
  late final _wire__crate__api__client__TorService_open_session =
      _wire__crate__api__client__TorService_open_sessionPtr
          .asFunction<void Function(int, int, int, int)>();

  void wire__crate__api__client__TorService_probe(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> host,
    int port,
    int timeout_ms,
  ) {
    return _wire__crate__api__client__TorService_probe(
      port_,
      that,
      host,
      port,
      timeout_ms,
    );
  }

  late final _wire__crate__api__client__TorService_probePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint16,
            ffi.Uint32,
          )
        >
      >('frbgen_onion_wire__crate__api__client__TorService_probe');
  late final _wire__crate__api__client__TorService_probe =
      _wire__crate__api__client__TorService_probePtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
            )
          >();

  void wire__crate__api__client__TorService_proxy_is_alive(
    int port_,
    int that,
  ) {
    return _wire__crate__api__client__TorService_proxy_is_alive(port_, that);
  }

  late final _wire__crate__api__client__TorService_proxy_is_alivePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__client__TorService_proxy_is_alive',
      );
  late final _wire__crate__api__client__TorService_proxy_is_alive =
      _wire__crate__api__client__TorService_proxy_is_alivePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__client__TorService_set_dormant(
    int port_,
    int that,
    bool dormant,
  ) {
    return _wire__crate__api__client__TorService_set_dormant(
      port_,
      that,
      dormant,
    );
  }

  late final _wire__crate__api__client__TorService_set_dormantPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Bool)>
      >('frbgen_onion_wire__crate__api__client__TorService_set_dormant');
  late final _wire__crate__api__client__TorService_set_dormant =
      _wire__crate__api__client__TorService_set_dormantPtr
          .asFunction<void Function(int, int, bool)>();

  void wire__crate__api__client__TorService_socks_port(int port_, int that) {
    return _wire__crate__api__client__TorService_socks_port(port_, that);
  }

  late final _wire__crate__api__client__TorService_socks_portPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__client__TorService_socks_port',
      );
  late final _wire__crate__api__client__TorService_socks_port =
      _wire__crate__api__client__TorService_socks_portPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__client__TorService_start(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> state_dir,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cache_dir,
    int socks_port,
    int policy,
  ) {
    return _wire__crate__api__client__TorService_start(
      port_,
      state_dir,
      cache_dir,
      socks_port,
      policy,
    );
  }

  late final _wire__crate__api__client__TorService_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint16,
            ffi.Int32,
          )
        >
      >('frbgen_onion_wire__crate__api__client__TorService_start');
  late final _wire__crate__api__client__TorService_start =
      _wire__crate__api__client__TorService_startPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
            )
          >();

  void wire__crate__api__client__TorService_start_with_snowflake(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> state_dir,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> cache_dir,
    int socks_port,
    int snowflake_port,
    int policy,
  ) {
    return _wire__crate__api__client__TorService_start_with_snowflake(
      port_,
      state_dir,
      cache_dir,
      socks_port,
      snowflake_port,
      policy,
    );
  }

  late final _wire__crate__api__client__TorService_start_with_snowflakePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Int32,
          )
        >
      >(
        'frbgen_onion_wire__crate__api__client__TorService_start_with_snowflake',
      );
  late final _wire__crate__api__client__TorService_start_with_snowflake =
      _wire__crate__api__client__TorService_start_with_snowflakePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              int,
            )
          >();

  void wire__crate__api__client__TorService_status(int port_, int that) {
    return _wire__crate__api__client__TorService_status(port_, that);
  }

  late final _wire__crate__api__client__TorService_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__client__TorService_status',
      );
  late final _wire__crate__api__client__TorService_status =
      _wire__crate__api__client__TorService_statusPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__client__TorService_stop(int port_, int that) {
    return _wire__crate__api__client__TorService_stop(port_, that);
  }

  late final _wire__crate__api__client__TorService_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__client__TorService_stop',
      );
  late final _wire__crate__api__client__TorService_stop =
      _wire__crate__api__client__TorService_stopPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__client__TorService_watch_status(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__client__TorService_watch_status(
      port_,
      that,
      sink,
    );
  }

  late final _wire__crate__api__client__TorService_watch_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_onion_wire__crate__api__client__TorService_watch_status');
  late final _wire__crate__api__client__TorService_watch_status =
      _wire__crate__api__client__TorService_watch_statusPtr
          .asFunction<
            void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__session__TorSession_proxy_is_alive(
    int port_,
    int that,
  ) {
    return _wire__crate__api__session__TorSession_proxy_is_alive(port_, that);
  }

  late final _wire__crate__api__session__TorSession_proxy_is_alivePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__session__TorSession_proxy_is_alive',
      );
  late final _wire__crate__api__session__TorSession_proxy_is_alive =
      _wire__crate__api__session__TorSession_proxy_is_alivePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__session__TorSession_socks_port(int port_, int that) {
    return _wire__crate__api__session__TorSession_socks_port(port_, that);
  }

  late final _wire__crate__api__session__TorSession_socks_portPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__session__TorSession_socks_port',
      );
  late final _wire__crate__api__session__TorSession_socks_port =
      _wire__crate__api__session__TorSession_socks_portPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__session__TorSession_stop(int port_, int that) {
    return _wire__crate__api__session__TorSession_stop(port_, that);
  }

  late final _wire__crate__api__session__TorSession_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_onion_wire__crate__api__session__TorSession_stop',
      );
  late final _wire__crate__api__session__TorSession_stop =
      _wire__crate__api__session__TorSession_stopPtr
          .asFunction<void Function(int, int)>();

  WireSyncRust2DartDco wire__crate__api__status__blockage_kind_is_user_visible(
    int that,
  ) {
    return _wire__crate__api__status__blockage_kind_is_user_visible(that);
  }

  late final _wire__crate__api__status__blockage_kind_is_user_visiblePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int32)>>(
        'frbgen_onion_wire__crate__api__status__blockage_kind_is_user_visible',
      );
  late final _wire__crate__api__status__blockage_kind_is_user_visible =
      _wire__crate__api__status__blockage_kind_is_user_visiblePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco
  wire__crate__api__status__blockage_kind_suggests_censorship(int that) {
    return _wire__crate__api__status__blockage_kind_suggests_censorship(that);
  }

  late final _wire__crate__api__status__blockage_kind_suggests_censorshipPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int32)>>(
        'frbgen_onion_wire__crate__api__status__blockage_kind_suggests_censorship',
      );
  late final _wire__crate__api__status__blockage_kind_suggests_censorship =
      _wire__crate__api__status__blockage_kind_suggests_censorshipPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__crate__api__session__socks_policy_default(int port_) {
    return _wire__crate__api__session__socks_policy_default(port_);
  }

  late final _wire__crate__api__session__socks_policy_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_onion_wire__crate__api__session__socks_policy_default',
      );
  late final _wire__crate__api__session__socks_policy_default =
      _wire__crate__api__session__socks_policy_defaultPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__status__tor_status_suggests_censorship(
    ffi.Pointer<wire_cst_tor_status> that,
  ) {
    return _wire__crate__api__status__tor_status_suggests_censorship(that);
  }

  late final _wire__crate__api__status__tor_status_suggests_censorshipPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_tor_status>)
        >
      >(
        'frbgen_onion_wire__crate__api__status__tor_status_suggests_censorship',
      );
  late final _wire__crate__api__status__tor_status_suggests_censorship =
      _wire__crate__api__status__tor_status_suggests_censorshipPtr
          .asFunction<
            WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_tor_status>)
          >();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_onion_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_onion_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_onion_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_onion_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_blockage> cst_new_box_autoadd_blockage() {
    return _cst_new_box_autoadd_blockage();
  }

  late final _cst_new_box_autoadd_blockagePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_blockage> Function()>>(
        'frbgen_onion_cst_new_box_autoadd_blockage',
      );
  late final _cst_new_box_autoadd_blockage = _cst_new_box_autoadd_blockagePtr
      .asFunction<ffi.Pointer<wire_cst_blockage> Function()>();

  ffi.Pointer<wire_cst_tor_status> cst_new_box_autoadd_tor_status() {
    return _cst_new_box_autoadd_tor_status();
  }

  late final _cst_new_box_autoadd_tor_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_tor_status> Function()>>(
        'frbgen_onion_cst_new_box_autoadd_tor_status',
      );
  late final _cst_new_box_autoadd_tor_status =
      _cst_new_box_autoadd_tor_statusPtr
          .asFunction<ffi.Pointer<wire_cst_tor_status> Function()>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_onion_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_blockage extends ffi.Struct {
  @ffi.Int32()
  external int kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}

final class wire_cst_tor_status extends ffi.Struct {
  @ffi.Float()
  external double fraction;

  @ffi.Bool()
  external bool ready_for_traffic;

  external ffi.Pointer<wire_cst_blockage> blockage;

  @ffi.Int32()
  external int transport;
}

final class wire_cst_tor_failure extends ffi.Struct {
  @ffi.Int32()
  external int kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> log_message;
}
