// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/error.dart';
import 'api/session.dart';
import 'api/status.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class OnionCore
    extends BaseEntrypoint<OnionCoreApi, OnionCoreApiImpl, OnionCoreWire> {
  @internal
  static final instance = OnionCore._();

  OnionCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    OnionCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required OnionCoreApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<OnionCoreApiImpl, OnionCoreWire> get apiImplConstructor =>
      OnionCoreApiImpl.new;

  @override
  WireConstructor<OnionCoreWire> get wireConstructor =>
      OnionCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1473461345;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'onion',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class OnionCoreApi extends BaseApi {
  Future<void> crateApiClientTorServiceBootstrap({required TorService that});

  Future<TorSession> crateApiClientTorServiceOpenSession({
    required TorService that,
    required int socksPort,
    required SocksPolicy policy,
  });

  Future<int> crateApiClientTorServiceProbe({
    required TorService that,
    required String host,
    required int port,
    required int timeoutMs,
  });

  Future<bool> crateApiClientTorServiceProxyIsAlive({required TorService that});

  Future<void> crateApiClientTorServiceSetDormant({
    required TorService that,
    required bool dormant,
  });

  Future<int> crateApiClientTorServiceSocksPort({required TorService that});

  Future<TorService> crateApiClientTorServiceStart({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required SocksPolicy policy,
  });

  Future<TorService> crateApiClientTorServiceStartWithSnowflake({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required int snowflakePort,
    required SocksPolicy policy,
  });

  Future<TorStatus> crateApiClientTorServiceStatus({required TorService that});

  Future<void> crateApiClientTorServiceStop({required TorService that});

  Stream<TorStatus> crateApiClientTorServiceWatchStatus({
    required TorService that,
  });

  Future<bool> crateApiSessionTorSessionProxyIsAlive({
    required TorSession that,
  });

  Future<int> crateApiSessionTorSessionSocksPort({required TorSession that});

  Future<void> crateApiSessionTorSessionStop({required TorSession that});

  bool crateApiStatusBlockageKindIsUserVisible({required BlockageKind that});

  bool crateApiStatusBlockageKindSuggestsCensorship({
    required BlockageKind that,
  });

  Future<SocksPolicy> crateApiSessionSocksPolicyDefault();

  bool crateApiStatusTorStatusSuggestsCensorship({required TorStatus that});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TorService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TorService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TorServicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TorSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TorSession;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TorSessionPtr;
}

class OnionCoreApiImpl extends OnionCoreApiImplPlatform
    implements OnionCoreApi {
  OnionCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClientTorServiceBootstrap({required TorService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          return wire.wire__crate__api__client__TorService_bootstrap(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_tor_failure,
        ),
        constMeta: kCrateApiClientTorServiceBootstrapConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceBootstrapConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_bootstrap",
        argNames: ["that"],
      );

  @override
  Future<TorSession> crateApiClientTorServiceOpenSession({
    required TorService that,
    required int socksPort,
    required SocksPolicy policy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          var arg1 = cst_encode_u_16(socksPort);
          var arg2 = cst_encode_socks_policy(policy);
          return wire.wire__crate__api__client__TorService_open_session(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession,
          decodeErrorData: dco_decode_tor_failure,
        ),
        constMeta: kCrateApiClientTorServiceOpenSessionConstMeta,
        argValues: [that, socksPort, policy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceOpenSessionConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_open_session",
        argNames: ["that", "socksPort", "policy"],
      );

  @override
  Future<int> crateApiClientTorServiceProbe({
    required TorService that,
    required String host,
    required int port,
    required int timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          var arg1 = cst_encode_String(host);
          var arg2 = cst_encode_u_16(port);
          var arg3 = cst_encode_u_32(timeoutMs);
          return wire.wire__crate__api__client__TorService_probe(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_32,
          decodeErrorData: dco_decode_tor_failure,
        ),
        constMeta: kCrateApiClientTorServiceProbeConstMeta,
        argValues: [that, host, port, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceProbeConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_probe",
        argNames: ["that", "host", "port", "timeoutMs"],
      );

  @override
  Future<bool> crateApiClientTorServiceProxyIsAlive({
    required TorService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          return wire.wire__crate__api__client__TorService_proxy_is_alive(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorServiceProxyIsAliveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceProxyIsAliveConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_proxy_is_alive",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiClientTorServiceSetDormant({
    required TorService that,
    required bool dormant,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          var arg1 = cst_encode_bool(dormant);
          return wire.wire__crate__api__client__TorService_set_dormant(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorServiceSetDormantConstMeta,
        argValues: [that, dormant],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceSetDormantConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_set_dormant",
        argNames: ["that", "dormant"],
      );

  @override
  Future<int> crateApiClientTorServiceSocksPort({required TorService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          return wire.wire__crate__api__client__TorService_socks_port(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorServiceSocksPortConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceSocksPortConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_socks_port",
        argNames: ["that"],
      );

  @override
  Future<TorService> crateApiClientTorServiceStart({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required SocksPolicy policy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(stateDir);
          var arg1 = cst_encode_String(cacheDir);
          var arg2 = cst_encode_u_16(socksPort);
          var arg3 = cst_encode_socks_policy(policy);
          return wire.wire__crate__api__client__TorService_start(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService,
          decodeErrorData: dco_decode_tor_failure,
        ),
        constMeta: kCrateApiClientTorServiceStartConstMeta,
        argValues: [stateDir, cacheDir, socksPort, policy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceStartConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_start",
        argNames: ["stateDir", "cacheDir", "socksPort", "policy"],
      );

  @override
  Future<TorService> crateApiClientTorServiceStartWithSnowflake({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required int snowflakePort,
    required SocksPolicy policy,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(stateDir);
          var arg1 = cst_encode_String(cacheDir);
          var arg2 = cst_encode_u_16(socksPort);
          var arg3 = cst_encode_u_16(snowflakePort);
          var arg4 = cst_encode_socks_policy(policy);
          return wire.wire__crate__api__client__TorService_start_with_snowflake(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService,
          decodeErrorData: dco_decode_tor_failure,
        ),
        constMeta: kCrateApiClientTorServiceStartWithSnowflakeConstMeta,
        argValues: [stateDir, cacheDir, socksPort, snowflakePort, policy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceStartWithSnowflakeConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_start_with_snowflake",
        argNames: [
          "stateDir",
          "cacheDir",
          "socksPort",
          "snowflakePort",
          "policy",
        ],
      );

  @override
  Future<TorStatus> crateApiClientTorServiceStatus({required TorService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          return wire.wire__crate__api__client__TorService_status(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_tor_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorServiceStatusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceStatusConstMeta =>
      const TaskConstMeta(debugName: "TorService_status", argNames: ["that"]);

  @override
  Future<void> crateApiClientTorServiceStop({required TorService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                that,
              );
          return wire.wire__crate__api__client__TorService_stop(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorServiceStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorServiceStopConstMeta =>
      const TaskConstMeta(debugName: "TorService_stop", argNames: ["that"]);

  @override
  Stream<TorStatus> crateApiClientTorServiceWatchStatus({
    required TorService that,
  }) {
    final sink = RustStreamSink<TorStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 =
                cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
                  that,
                );
            var arg1 = cst_encode_StreamSink_tor_status_Dco(sink);
            return wire.wire__crate__api__client__TorService_watch_status(
              port_,
              arg0,
              arg1,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiClientTorServiceWatchStatusConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientTorServiceWatchStatusConstMeta =>
      const TaskConstMeta(
        debugName: "TorService_watch_status",
        argNames: ["that", "sink"],
      );

  @override
  Future<bool> crateApiSessionTorSessionProxyIsAlive({
    required TorSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
                that,
              );
          return wire.wire__crate__api__session__TorSession_proxy_is_alive(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionTorSessionProxyIsAliveConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionTorSessionProxyIsAliveConstMeta =>
      const TaskConstMeta(
        debugName: "TorSession_proxy_is_alive",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiSessionTorSessionSocksPort({required TorSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
                that,
              );
          return wire.wire__crate__api__session__TorSession_socks_port(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionTorSessionSocksPortConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionTorSessionSocksPortConstMeta =>
      const TaskConstMeta(
        debugName: "TorSession_socks_port",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSessionTorSessionStop({required TorSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
                that,
              );
          return wire.wire__crate__api__session__TorSession_stop(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionTorSessionStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionTorSessionStopConstMeta =>
      const TaskConstMeta(debugName: "TorSession_stop", argNames: ["that"]);

  @override
  bool crateApiStatusBlockageKindIsUserVisible({required BlockageKind that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_blockage_kind(that);
          return wire.wire__crate__api__status__blockage_kind_is_user_visible(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatusBlockageKindIsUserVisibleConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusBlockageKindIsUserVisibleConstMeta =>
      const TaskConstMeta(
        debugName: "blockage_kind_is_user_visible",
        argNames: ["that"],
      );

  @override
  bool crateApiStatusBlockageKindSuggestsCensorship({
    required BlockageKind that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_blockage_kind(that);
          return wire
              .wire__crate__api__status__blockage_kind_suggests_censorship(
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatusBlockageKindSuggestsCensorshipConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusBlockageKindSuggestsCensorshipConstMeta =>
      const TaskConstMeta(
        debugName: "blockage_kind_suggests_censorship",
        argNames: ["that"],
      );

  @override
  Future<SocksPolicy> crateApiSessionSocksPolicyDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__session__socks_policy_default(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_socks_policy,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionSocksPolicyDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSocksPolicyDefaultConstMeta =>
      const TaskConstMeta(debugName: "socks_policy_default", argNames: []);

  @override
  bool crateApiStatusTorStatusSuggestsCensorship({required TorStatus that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_box_autoadd_tor_status(that);
          return wire.wire__crate__api__status__tor_status_suggests_censorship(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatusTorStatusSuggestsCensorshipConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatusTorStatusSuggestsCensorshipConstMeta =>
      const TaskConstMeta(
        debugName: "tor_status_suggests_censorship",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TorService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TorService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TorSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TorSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  TorService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<TorStatus> dco_decode_StreamSink_tor_status_Dco(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Blockage dco_decode_blockage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Blockage(
      kind: dco_decode_blockage_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  BlockageKind dco_decode_blockage_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlockageKind.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Blockage dco_decode_box_autoadd_blockage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_blockage(raw);
  }

  @protected
  TorStatus dco_decode_box_autoadd_tor_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tor_status(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Blockage? dco_decode_opt_box_autoadd_blockage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_blockage(raw);
  }

  @protected
  SocksPolicy dco_decode_socks_policy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SocksPolicy.values[raw as int];
  }

  @protected
  TorFailure dco_decode_tor_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TorFailure(
      kind: dco_decode_tor_failure_kind(arr[0]),
      logMessage: dco_decode_String(arr[1]),
    );
  }

  @protected
  TorFailureKind dco_decode_tor_failure_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorFailureKind.values[raw as int];
  }

  @protected
  TorStatus dco_decode_tor_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TorStatus(
      fraction: dco_decode_f_32(arr[0]),
      readyForTraffic: dco_decode_bool(arr[1]),
      blockage: dco_decode_opt_box_autoadd_blockage(arr[2]),
      transport: dco_decode_tor_transport(arr[3]),
    );
  }

  @protected
  TorTransport dco_decode_tor_transport(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorTransport.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  TorService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TorSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TorService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TorSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TorService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TorSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<TorStatus> sse_decode_StreamSink_tor_status_Dco(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Blockage sse_decode_blockage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_blockage_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return Blockage(kind: var_kind, message: var_message);
  }

  @protected
  BlockageKind sse_decode_blockage_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BlockageKind.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Blockage sse_decode_box_autoadd_blockage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_blockage(deserializer));
  }

  @protected
  TorStatus sse_decode_box_autoadd_tor_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tor_status(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Blockage? sse_decode_opt_box_autoadd_blockage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_blockage(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SocksPolicy sse_decode_socks_policy(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SocksPolicy.values[inner];
  }

  @protected
  TorFailure sse_decode_tor_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_tor_failure_kind(deserializer);
    var var_logMessage = sse_decode_String(deserializer);
    return TorFailure(kind: var_kind, logMessage: var_logMessage);
  }

  @protected
  TorFailureKind sse_decode_tor_failure_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TorFailureKind.values[inner];
  }

  @protected
  TorStatus sse_decode_tor_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fraction = sse_decode_f_32(deserializer);
    var var_readyForTraffic = sse_decode_bool(deserializer);
    var var_blockage = sse_decode_opt_box_autoadd_blockage(deserializer);
    var var_transport = sse_decode_tor_transport(deserializer);
    return TorStatus(
      fraction: var_fraction,
      readyForTraffic: var_readyForTraffic,
      blockage: var_blockage,
      transport: var_transport,
    );
  }

  @protected
  TorTransport sse_decode_tor_transport(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TorTransport.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorServiceImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorSessionImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorServiceImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorSessionImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorServiceImpl).frbInternalCstEncode();
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as TorSessionImpl).frbInternalCstEncode();
  }

  @protected
  int cst_encode_blockage_kind(BlockageKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_socks_policy(SocksPolicy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_tor_failure_kind(TorFailureKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_tor_transport(TorTransport raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorService(
    TorService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorSession(
    TorSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TorSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_tor_status_Dco(
    RustStreamSink<TorStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_tor_status,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_blockage(Blockage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_blockage_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_blockage_kind(BlockageKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_blockage(
    Blockage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_blockage(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tor_status(
    TorStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tor_status(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_blockage(
    Blockage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_blockage(self, serializer);
    }
  }

  @protected
  void sse_encode_socks_policy(SocksPolicy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tor_failure(TorFailure self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tor_failure_kind(self.kind, serializer);
    sse_encode_String(self.logMessage, serializer);
  }

  @protected
  void sse_encode_tor_failure_kind(
    TorFailureKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tor_status(TorStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.fraction, serializer);
    sse_encode_bool(self.readyForTraffic, serializer);
    sse_encode_opt_box_autoadd_blockage(self.blockage, serializer);
    sse_encode_tor_transport(self.transport, serializer);
  }

  @protected
  void sse_encode_tor_transport(TorTransport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class TorServiceImpl extends RustOpaque implements TorService {
  // Not to be used by end users
  TorServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TorServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        OnionCore.instance.api.rust_arc_increment_strong_count_TorService,
    rustArcDecrementStrongCount:
        OnionCore.instance.api.rust_arc_decrement_strong_count_TorService,
    rustArcDecrementStrongCountPtr:
        OnionCore.instance.api.rust_arc_decrement_strong_count_TorServicePtr,
  );

  /// Bootstrap, resolving when the client is usable.
  Future<void> bootstrap() =>
      OnionCore.instance.api.crateApiClientTorServiceBootstrap(that: this);

  /// Open another loopback SOCKS listener with separate Tor circuits.
  ///
  /// Sessions share the root client's configuration, directory state,
  /// guards, channels, and transport. Their application streams never share
  /// circuits with the default session or with one another.
  Future<TorSession> openSession({
    required int socksPort,
    required SocksPolicy policy,
  }) => OnionCore.instance.api.crateApiClientTorServiceOpenSession(
    that: this,
    socksPort: socksPort,
    policy: policy,
  );

  /// Open and immediately close a circuit to `host:port`, returning how long
  /// it took.
  ///
  /// This is the canary that separates "the Tor network is unreachable" from
  /// "an application hidden service is down". It goes through
  /// `TorClient::connect`
  /// directly, bypassing both the SOCKS listener and the application's
  /// servers, so a success here means Tor genuinely carries traffic.
  ///
  /// `ready_for_traffic` is not a substitute: it means "a request can be
  /// started", not "a request succeeded".
  ///
  /// Times are milliseconds: FRB has no outbound mapping for
  /// `std::time::Duration`, and an integer keeps `chrono` out of our types.
  ///
  /// No failure returned here names `host`. The probe target is a hidden
  /// service the user is reaching over Tor, and these strings are logged;
  /// `socks::handle_conn` keeps destinations out of its errors for the same
  /// reason, so this must not be the one place that reintroduces them.
  Future<int> probe({
    required String host,
    required int port,
    required int timeoutMs,
  }) => OnionCore.instance.api.crateApiClientTorServiceProbe(
    that: this,
    host: host,
    port: port,
    timeoutMs: timeoutMs,
  );

  /// Whether the SOCKS accept loop is still running.
  ///
  /// It can die on its own — a listener error ends it — after which every
  /// connection to [`TorService::socks_port`] is refused. Without this, the
  /// app would see unexplained transport failures and blame the
  /// network. Cheap enough to check before handing the port out.
  Future<bool> proxyIsAlive() =>
      OnionCore.instance.api.crateApiClientTorServiceProxyIsAlive(that: this);

  /// Put background activity to sleep, or wake it up.
  Future<void> setDormant({required bool dormant}) => OnionCore.instance.api
      .crateApiClientTorServiceSetDormant(that: this, dormant: dormant);

  /// The port the SOCKS proxy is actually listening on.
  Future<int> socksPort() =>
      OnionCore.instance.api.crateApiClientTorServiceSocksPort(that: this);

  /// Current readiness snapshot.
  Future<TorStatus> status() =>
      OnionCore.instance.api.crateApiClientTorServiceStatus(that: this);

  /// Stop the proxy listener, bootstrap, and status-forwarding tasks.
  ///
  /// Safe to call more than once. Keeping this as `&self` is required by the
  /// FFI boundary: a status-stream task may briefly hold another opaque
  /// reference, so consuming `self` could panic while decoding the call.
  Future<void> stop() =>
      OnionCore.instance.api.crateApiClientTorServiceStop(that: this);

  /// Forward readiness changes to Dart from the FRB async runtime.
  ///
  /// Same data as [`TorService::status_stream`], expressed as a
  /// `StreamSink` because that is the only stream shape
  /// `flutter_rust_bridge` generates for. The task ends when Dart drops the
  /// subscription, arti closes the channel, or [`TorService::stop`] runs.
  Stream<TorStatus> watchStatus() =>
      OnionCore.instance.api.crateApiClientTorServiceWatchStatus(that: this);
}

@sealed
class TorSessionImpl extends RustOpaque implements TorSession {
  // Not to be used by end users
  TorSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TorSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        OnionCore.instance.api.rust_arc_increment_strong_count_TorSession,
    rustArcDecrementStrongCount:
        OnionCore.instance.api.rust_arc_decrement_strong_count_TorSession,
    rustArcDecrementStrongCountPtr:
        OnionCore.instance.api.rust_arc_decrement_strong_count_TorSessionPtr,
  );

  /// Whether this session's SOCKS accept loop is still running.
  Future<bool> proxyIsAlive() =>
      OnionCore.instance.api.crateApiSessionTorSessionProxyIsAlive(that: this);

  /// The loopback SOCKS port assigned to this session.
  Future<int> socksPort() =>
      OnionCore.instance.api.crateApiSessionTorSessionSocksPort(that: this);

  /// Stop this session without affecting the shared Tor core or other sessions.
  Future<void> stop() =>
      OnionCore.instance.api.crateApiSessionTorSessionStop(that: this);
}
