name: bitbox_transport
description: USB and Bluetooth transport for BitBox02 hardware wallet
version: 0.1.0

environment:
  sdk: "3.12.2"
  flutter: "3.44.2"

dependencies:
  flutter:
    sdk: flutter
  bull_sdk:
    path: ../bull_sdk
  universal_ble: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bitbox.bitbox_flutter
        pluginClass: BitboxFlutterPlugin
