// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';
import 'status.dart';

// These functions are ignored because they are not marked as `pub`: `begin_stop`, `client`, `configure_snowflake`, `start_with_transport`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionRegistry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `status_stream`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorService>>
abstract class TorService implements RustOpaqueInterface {
  /// Bootstrap, resolving when the client is usable.
  Future<void> bootstrap();

  /// Open another loopback SOCKS listener with separate Tor circuits.
  ///
  /// Sessions share the root client's configuration, directory state,
  /// guards, channels, and transport. Their application streams never share
  /// circuits with the default session or with one another.
  Future<TorSession> openSession({
    required int socksPort,
    required SocksPolicy policy,
  });

  /// Open and immediately close a circuit to `host:port`, returning how long
  /// it took.
  ///
  /// This is the canary that separates "the Tor network is unreachable" from
  /// "an application hidden service is down". It goes through
  /// `TorClient::connect`
  /// directly, bypassing both the SOCKS listener and the application's
  /// servers, so a success here means Tor genuinely carries traffic.
  ///
  /// `ready_for_traffic` is not a substitute: it means "a request can be
  /// started", not "a request succeeded".
  ///
  /// Times are milliseconds: FRB has no outbound mapping for
  /// `std::time::Duration`, and an integer keeps `chrono` out of our types.
  ///
  /// No failure returned here names `host`. The probe target is a hidden
  /// service the user is reaching over Tor, and these strings are logged;
  /// `socks::handle_conn` keeps destinations out of its errors for the same
  /// reason, so this must not be the one place that reintroduces them.
  Future<int> probe({
    required String host,
    required int port,
    required int timeoutMs,
  });

  /// Whether the SOCKS accept loop is still running.
  ///
  /// It can die on its own — a listener error ends it — after which every
  /// connection to [`TorService::socks_port`] is refused. Without this, the
  /// app would see unexplained transport failures and blame the
  /// network. Cheap enough to check before handing the port out.
  Future<bool> proxyIsAlive();

  /// Put background activity to sleep, or wake it up.
  Future<void> setDormant({required bool dormant});

  /// The port the SOCKS proxy is actually listening on.
  Future<int> socksPort();

  /// Create the client and bind the SOCKS listener. Does not bootstrap.
  ///
  /// `socks_port` may be `0` to let the OS choose; read the real value back
  /// from [`TorService::socks_port`].
  static Future<TorService> start({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required SocksPolicy policy,
  }) => OnionCore.instance.api.crateApiClientTorServiceStart(
    stateDir: stateDir,
    cacheDir: cacheDir,
    socksPort: socksPort,
    policy: policy,
  );

  /// Create a client routed through an already-running Snowflake SOCKS proxy.
  ///
  /// The proxy is unmanaged: the native plugin owns its process-wide
  /// lifecycle while Arti only receives its loopback port.
  static Future<TorService> startWithSnowflake({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
    required int snowflakePort,
    required SocksPolicy policy,
  }) => OnionCore.instance.api.crateApiClientTorServiceStartWithSnowflake(
    stateDir: stateDir,
    cacheDir: cacheDir,
    socksPort: socksPort,
    snowflakePort: snowflakePort,
    policy: policy,
  );

  /// Current readiness snapshot.
  Future<TorStatus> status();

  /// Stop the proxy listener, bootstrap, and status-forwarding tasks.
  ///
  /// Safe to call more than once. Keeping this as `&self` is required by the
  /// FFI boundary: a status-stream task may briefly hold another opaque
  /// reference, so consuming `self` could panic while decoding the call.
  Future<void> stop();

  /// Forward readiness changes to Dart from the FRB async runtime.
  ///
  /// Same data as [`TorService::status_stream`], expressed as a
  /// `StreamSink` because that is the only stream shape
  /// `flutter_rust_bridge` generates for. The task ends when Dart drops the
  /// subscription, arti closes the channel, or [`TorService::stop`] runs.
  Stream<TorStatus> watchStatus();
}
