// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `bootstrap`, `configuration`, `connect`, `listener_bind`, `new`, `not_running`, `timeout`, `unexpected`

/// A modelled, recoverable failure.
///
/// `log_message` carries developer detail. It is logged on our side and must
/// never be rendered to the end user verbatim — the Dart layer maps
/// [`TorFailure::kind`] to a localized string.
class TorFailure implements FrbException {
  /// The programmatic discriminant.
  final TorFailureKind kind;

  /// Developer-facing detail. Never user-facing.
  final String logMessage;

  const TorFailure({required this.kind, required this.logMessage});

  @override
  int get hashCode => kind.hashCode ^ logMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          logMessage == other.logMessage;
}

/// Why a Tor operation failed.
///
/// Mirrors the shape the Dart side needs, not arti's internal taxonomy.
enum TorFailureKind {
  /// The state/cache directory could not be prepared, or the config was rejected.
  configuration,

  /// The local SOCKS listener could not be bound.
  listenerBind,

  /// Bootstrap did not complete. Inspect the last [`crate::api::status::TorStatus`]
  /// for a `blockage` explaining why.
  bootstrap,

  /// A connection through Tor failed (used by the reachability probe).
  connect,

  /// The probe did not complete within its deadline.
  timeout,

  /// The service was not started, or was already stopped.
  notRunning,

  /// Anything we did not model. `logMessage` is for our logs, never for the user.
  unexpected,
}
