// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abort`, `allows`, `client`, `downgrade`, `is_onion_host`, `proxy_is_alive`, `start`, `stop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TorSessionInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `drop`, `eq`, `fmt`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorSession>>
abstract class TorSession implements RustOpaqueInterface {
  /// Whether this session's SOCKS accept loop is still running.
  Future<bool> proxyIsAlive();

  /// The loopback SOCKS port assigned to this session.
  Future<int> socksPort();

  /// Stop this session without affecting the shared Tor core or other sessions.
  Future<void> stop();
}

/// Which destinations a session's SOCKS listener will relay.
///
/// The library default is [`SocksPolicy::Any`]: a Tor proxy that refuses the
/// clearnet is not a Tor proxy, and deciding otherwise is the embedding
/// application's business, not this package's.
enum SocksPolicy {
  /// Relay any destination the Tor network can reach.
  any,

  /// Relay `.onion` destinations only; answer anything else `NOT_ALLOWED`.
  ///
  /// Worth knowing before choosing it: a loopback TCP port is host-local,
  /// not process-private, and this proxy performs no authentication, so any
  /// process on the device that finds the port can use it. An application
  /// that only ever contacts hidden services can pick this to bound what
  /// that exposure is worth — it narrows the open door, it does not close
  /// it. Closing it needs SOCKS credentials or an `AF_UNIX` socket.
  onionOnly;

  static Future<SocksPolicy> default_() =>
      OnionCore.instance.api.crateApiSessionSocksPolicyDefault();
}
