// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_bootstrap`, `stopped`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// A blockage: a machine-readable kind plus arti's human-readable detail.
class Blockage {
  /// Programmatic discriminant, safe to switch on.
  final BlockageKind kind;

  /// arti's own wording. Developer/diagnostic detail, not a localized string.
  final String message;

  const Blockage({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Blockage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Why the client believes it cannot make progress.
///
/// Maps [`arti_client::status::BlockageKind`], which is `#[non_exhaustive]`
/// upstream — hence [`BlockageKind::Other`].
enum BlockageKind {
  /// Bootstrap has not been requested yet.
  ///
  /// Not a fault. arti reports this whenever the client was built with
  /// `BootstrapBehavior::Manual` and has not been told to start, which is
  /// exactly our steady state between `start()` and `bootstrap()`. It must
  /// never be shown to the user as a problem.
  notStarted,

  /// No TCP connectivity at all.
  offline,

  /// TCP works but the Tor handshake does not complete.
  ///
  /// This is the censorship signature: a middlebox is inspecting and
  /// dropping Tor traffic. It is the condition that should offer the user
  /// circumvention, and the one plain bridges do *not* fix.
  filtering,

  /// Some other problem reaching the Tor network.
  cantReachTor,

  /// The device clock is wrong enough to break certificate validation.
  clockSkewed,

  /// Directory information could not be assembled, with no obvious
  /// connection-level cause.
  cantBootstrap,

  /// A blockage kind added upstream after this mapping was written.
  other;

  /// Whether this blockage is worth telling the user about at all.
  ///
  /// [`BlockageKind::NotStarted`] is arti describing our own deliberate
  /// `Manual` bootstrap mode back to us; reporting it would put a permanent
  /// bogus warning on screen before the user has done anything.
  bool isUserVisible() => OnionCore.instance.api
      .crateApiStatusBlockageKindIsUserVisible(that: this);

  /// Whether this blockage is consistent with active network censorship.
  ///
  /// Advisory only. arti documents `blocked()` as a best-effort diagnostic
  /// that "may declare that Arti is stuck for reasons that are incorrect".
  /// Use it to *offer* circumvention, never to assert to the user that they
  /// are being censored.
  bool suggestsCensorship() => OnionCore.instance.api
      .crateApiStatusBlockageKindSuggestsCensorship(that: this);
}

/// A snapshot of how ready the client is.
class TorStatus {
  /// Rough bootstrap progress, 0.0 (just started) to 1.0 (ready).
  final double fraction;

  /// Whether a new request can be acted on right now.
  final bool readyForTraffic;

  /// Present when arti believes it is stuck.
  final Blockage? blockage;

  /// Route configured for this client.
  ///
  /// This does not by itself mean that Snowflake connected. Consumers must
  /// also require [`TorStatus::ready_for_traffic`] before claiming that.
  final TorTransport transport;

  const TorStatus({
    required this.fraction,
    required this.readyForTraffic,
    this.blockage,
    required this.transport,
  });

  /// Whether the client is stuck in a way consistent with censorship.
  bool suggestsCensorship() => OnionCore.instance.api
      .crateApiStatusTorStatusSuggestsCensorship(that: this);

  @override
  int get hashCode =>
      fraction.hashCode ^
      readyForTraffic.hashCode ^
      blockage.hashCode ^
      transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorStatus &&
          runtimeType == other.runtimeType &&
          fraction == other.fraction &&
          readyForTraffic == other.readyForTraffic &&
          blockage == other.blockage &&
          transport == other.transport;
}

/// Network transport configured for this Tor client.
enum TorTransport {
  /// Connect to Tor relays directly.
  direct,

  /// Reach a Tor bridge through the Snowflake pluggable transport.
  snowflake,
}
